<?php
/** 
 * @file
 * All functionality of custom_redirection module.
 */

/**
 * Implements hook_menu().
 */
function custom_redirection_menu() {
  $menu['admin/custom_redirection/manage'] = array(
    'title' => 'My login',
    'page callback' => 'custom_redirection_manage_item_page',
    'access callback' => TRUE,
  );
  return $menu;
}
/**
 * custom redirection menu calling the form.
 */
function custom_redirection_manage_item_page() {
  return drupal_get_form('custom_redirection_form');
}
/**
 * custom redirection module checking whether any data or present in table.
 */
function custom_redirection_form($form, &$form_state) {
  $rowcount = db_query('SELECT `id`, `login_destination`  FROM {custom_redirection} WHERE `id` = 1')->rowCount();
  $result = db_query('SELECT id, login_destination  FROM {custom_redirection} WHERE id = 1')->fetchObject();
  if ($rowcount != 0) {
    $form['#attributes']['enctype'] = 'multipart/form-data';
    $form['id'] = array(
      '#type' => 'hidden',
      '#default_value' => $result->id,
    );
    $form['login_destination'] = array(
      '#title' => t('Enter a Login Destination'),
      '#type' => 'textfield',
      '#default_value' => $result->login_destination,
      '#description' => t('Please enter the login destination after login success. example "dashboard"'),
    );
    $form['mode'] = array(
      '#type' => 'hidden',
      '#default_value' => 'update',
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Update'),
    );
  }
  else {
    $form['id'] = array(
      '#type' => 'hidden',
      '#default_value' => '1',
    );
    $form['login_destination'] = array(
      '#title' => t('Enter a Login Destination'),
      '#type' => 'textfield',
      '#default_value' => '',
      '#description' => t('Please enter the login destination after login success. example "dashboard"'),
    );
    $form['mode'] = array(
      '#type' => 'hidden',
      '#default_value' => 'save',
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Save'),
    );
  }
  return $form;
}
/**
 * Submitting form to update the changes / inserting the new data.
 */
function custom_redirection_form_submit($form, &$form_state) {
  if ($form_state['values']['mode'] != 'save') {
    db_update('custom_redirection')
    ->fields(array('login_destination' => $form_state['values']['login_destination']))
    ->condition('id', $form_state['values']['id'])
    ->execute();
    $form_state['redirect'] = 'admin/custom_redirection/manage';
  }
  else {
    $query = db_insert('custom_redirection')
    ->fields(array('id' => '1', 'login_destination' => $form_state['values']['login_destination']))
    ->execute();
    $form_state['redirect'] = 'admin/custom_redirection/manage';
  }
}
/**
 * Hook_user_login used to do redirection as per configured in custom_redirection.
 */
function custom_redirection_user_login(&$edit, $account) {
  $result = db_query('SELECT id, login_destination  FROM {custom_redirection} WHERE id = 1')->fetchObject();
  if (count($result) == 1) {
    drupal_goto($result->login_destination);
  }
}
